/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundUploader: typeof import('./src/components/BackgroundUploader.vue')['default']
    BrushSizePanel: typeof import('./src/components/BrushSizePanel.vue')['default']
    CanvasArea: typeof import('./src/components/CanvasArea.vue')['default']
    CanvasToolbar: typeof import('./src/components/CanvasToolbar.vue')['default']
    CollageSeriesPanel: typeof import('./src/components/CollageSeriesPanel.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ContainerToolbar: typeof import('./src/components/ContainerToolbar.vue')['default']
    DataEditor: typeof import('./src/components/DataEditor.vue')['default']
    ElTable: typeof import('element-plus')['ElTable']
    ElTableColumn: typeof import('element-plus')['ElTableColumn']
    EmitterToolbar: typeof import('./src/components/EmitterToolbar.vue')['default']
    FirstToolbar: typeof import('./src/components/FirstToolbar.vue')['default']
    ForceToolbar: typeof import('./src/components/ForceToolbar.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MarkerToolbar: typeof import('./src/components/MarkerToolbar.vue')['default']
    ObjectActionButtons: typeof import('./src/components/ObjectActionButtons.vue')['default']
    ObjectColorPicker: typeof import('./src/components/ObjectColorPicker.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    PaperCanvas: typeof import('./src/components/paperCanvas.vue')['default']
    ResizableContainer: typeof import('./src/components/ResizableContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningStatusIndicator: typeof import('./src/components/RunningStatusIndicator.vue')['default']
    SubCanvasArea: typeof import('./src/components/subCanvasArea.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    ToastPanel: typeof import('./src/components/ToastPanel.vue')['default']
  }
}
