/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundUploader: typeof import('./src/components/BackgroundUploader.vue')['default']
    BrushSizePanel: typeof import('./src/components/BrushSizePanel.vue')['default']
    CanvasArea: typeof import('./src/components/CanvasArea.vue')['default']
    CanvasToolbar: typeof import('./src/components/CanvasToolbar.vue')['default']
    ClosePathConfirm: typeof import('./src/components/ClosePathConfirm.vue')['default']
    CollageSeriesPanel: typeof import('./src/components/CollageSeriesPanel.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ContainerToolbar: typeof import('./src/components/ContainerToolbar.vue')['default']
    DataEditor: typeof import('./src/components/DataEditor.vue')['default']
    DataMapping: typeof import('./src/components/DataMapping.vue')['default']
    ElInput: typeof import('element-plus')['ElInput']
    ElOption: typeof import('element-plus')['ElOption']
    ElPopconfirm: typeof import('element-plus')['ElPopconfirm']
    ElRadio: typeof import('element-plus')['ElRadio']
    ElRadioGroup: typeof import('element-plus')['ElRadioGroup']
    ElSelect: typeof import('element-plus')['ElSelect']
    ElSlider: typeof import('element-plus')['ElSlider']
    ElSwitch: typeof import('element-plus')['ElSwitch']
    ElTable: typeof import('element-plus')['ElTable']
    ElTableColumn: typeof import('element-plus')['ElTableColumn']
    EmitterToolbar: typeof import('./src/components/EmitterToolbar.vue')['default']
    FirstToolbar: typeof import('./src/components/FirstToolbar.vue')['default']
    ForceToolbar: typeof import('./src/components/ForceToolbar.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HoverInfoPanel: typeof import('./src/components/hoverInfoPanel.vue')['default']
    MarkerCanvasArea: typeof import('./src/components/MarkerCanvasArea.vue')['default']
    MarkerLibrary: typeof import('./src/components/markerLibrary.vue')['default']
    MarkerMappingPanel: typeof import('./src/components/MarkerMappingPanel.vue')['default']
    MarkerObjectActionButtons: typeof import('./src/components/MarkerObjectActionButtons.vue')['default']
    MarkerToolbar: typeof import('./src/components/MarkerToolbar.vue')['default']
    ObjectActionButtons: typeof import('./src/components/ObjectActionButtons.vue')['default']
    ObjectColorPicker: typeof import('./src/components/ObjectColorPicker.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    PaperCanvas: typeof import('./src/components/paperCanvas.vue')['default']
    ResizableContainer: typeof import('./src/components/ResizableContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningStatusIndicator: typeof import('./src/components/RunningStatusIndicator.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    SubCanvasArea: typeof import('./src/components/subCanvasArea.vue')['default']
    SubMarkerToolbar: typeof import('./src/components/subMarkerToolbar.vue')['default']
    SubObjectActionButtons: typeof import('./src/components/SubObjectActionButtons.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TableData: typeof import('./src/components/TableData.vue')['default']
    TableUploadArea: typeof import('./src/components/TableUploadArea.vue')['default']
    ToastPanel: typeof import('./src/components/ToastPanel.vue')['default']
  }
}
