/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrushSizePanel: typeof import('./src/components/BrushSizePanel.vue')['default']
    CanvasArea: typeof import('./src/components/CanvasArea.vue')['default']
    CanvasToolbar: typeof import('./src/components/CanvasToolbar.vue')['default']
    DataEditor: typeof import('./src/components/DataEditor.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    ResizableContainer: typeof import('./src/components/ResizableContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastPanel: typeof import('./src/components/ToastPanel.vue')['default']
  }
}
